### ISSUE TITLE
Remove unnecessary function 

### ISSUE THREAD

**Issue by ksmotiv8** [momentohq/momento-cli#24]
https://github.com/momentohq/momento-cli/blob/5578abe444fc8fac7f1781efbe0414c25bfd5c48/src/utils/file.rs#L78-L85

The function referenced above is unnecessary - This assertion is based on reading the documentation for `create_dir_all` which indicates: "Recursively create a directory and all of its parent components if they are missing."

https://doc.rust-lang.org/std/fs/fn.create_dir_all.html

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=36ce82190ca04d07321b69a2152ebd3d

the line below can simply be replaced with `fs::create_dir_all(path)` 
https://github.com/momentohq/momento-cli/blob/5578abe444fc8fac7f1781efbe0414c25bfd5c48/src/commands/configure/configure.rs#L26

I also do not understand why this is an async function. Cool tool - but a) why make this method by async to begin with if b) the only time you use it is when you do a .await anyway for c) a single threaded app? Eager to learn more as I learned something last time I asked this question in TS land :).

**Comment by kvcache** [comment]
do you know what happens when you call create_dir_all on a path that already exists but is a file not a directory?

**Comment by ksmotiv8** [comment]
> do you know what happens when you call create_dir_all on a path that already exists but is a file not a directory?

I get an Ok() if the dir already exists. However, if the path exists as a file, I get the following error:
failed to created directory dir, error: File exists (os error 17)'

This is not much different, meanwhile, than our current behavior - where we silently chose not to just create a dir if a file is there and assume its a directory.

**Comment by gautamomento** [comment]
![Image from iOS](https://user-images.githubusercontent.com/89037104/143954740-afc950d4-aa50-4c90-a4bd-b888507a4b77.jpg)

**Comment by bruuuuuuuce** [comment]
The main advantage of making this async is so that we are not blocking the users thread while we are performing any async tasks. 

Awaiting on an async task is different than blocking the thread for it, we are just awaiting on it to complete. 

This is a single threaded app, and it honestly will probably not matter for file io, but we definetly want have our api calls to momento be asynchronous. Since we are using the tokio runtime, i stuck with using the tokio async filesystem more for consistency than anything. 

 Looking over this issue again, I think you are correct in that we don't need to wrap this function, and we should be able to use the built in `create_dir_all` from tokio.  I have added integration tests that should catch these same errors in the future.
