### ISSUE TITLE
Add bottle install for m1 macs

### ISSUE THREAD

**Issue by kvcache** [momentohq/momento-cli#65]
While I'm waiting for `brew upgrade momento-cli` to finish I have time to open an issue that it should upgrade in about 3 seconds, downloading a binary rather than building from source. It's great to be able to build on any unsupported platform, but for the likely suspects it would be very nice to just have the pre-baked bits!

**Comment by poppoerika** [comment]
After trying to figure out some time and discussing with @eaddingtonwhite and @bruuuuuuuce, there are a few options to bottle ARM binary:
- Manually arrach the ARM tar file created in the homebrew-tap repo in the test.yml workflow
- Move to homebrew-core instead of maintaining our tap. We found many examples of ARM bottles ([here](https://github.com/Homebrew/homebrew-core/tree/master/Formula)), however our repo needs to get certain numbers of stars.
Publishing our Rust SDK is higher priority so we pause this ticket and revisit what other possible options are avialable.

**Comment by cprice404** [comment]
can look at `bat` rust CLI tool as an example for packaging.

Would like to have both intel and ARM binaries linked in our releases whenever we do a release.

**Comment by poppoerika** [comment]
@schwern  This is the PR I was working on to add ARM binary to the GH release workflow: https://github.com/momentohq/homebrew-tap/pull/54

**Comment by cprice404** [comment]
@schwern here is where we are building the two flavors of mac binaries for `mm`:

https://github.com/momentohq/mm/blob/main/.github/workflows/push.yml#L48-L55

**Comment by kvcache** [comment]
```
brew install momento-cli  442.50s user 61.46s system 258% cpu 5:21.05 total
```

and it has messed up my laptop's compiler:
```
➜  which rustc
/opt/homebrew/bin/rustc
```

For others, I fixed my machine after installing `momento-cli` by doing `brew uninstall rust`
```
➜  which rustc
/Users/kenny/.cargo/bin/rustc
```

`rust` was the only vestigial homebrew dependency left over from the installation and it _looks_ like brew uninstalling it is enough to restore my environment, but if your machine is polluted by this install make sure you get rid of any other `Installing dependencies for momentohq/tap/momento-cli: **dependency-name**` dependencies!

**Comment by cprice404** [comment]
@schwern a few note for getting started on this:

1. The docs for installing say that users should run `brew install`, but it's likely that our changes will temporarily break the brew installation process while we are iterating on them.  Therefore, the first goal should just be to figure out how to build the mac binaries for both intel and ARM, and attach them to a github release.
2. Then we should update the docs to temporarily provide a curl command for getting the binaries from the github release.
3. Then we should work on the brew process.
4. Then we should switch the docs back over.

For step 1 - doing the dev work via the "manual release" action is a very slow process, and I also currently have some ongoing work to fix the linux builds that is going to conflict with what you are trying to do.  So what I would suggest is that we manually create a "release" via the github UI, and then you add a temporary new github action that runs on your subsequent PRs, to build the binaries and attach them to that (hard-coded, hand-created) release.  Once you have that working we can move the logic from your action over into the main one.  Hopefully by then the dust will have settled from the linux one.

**Comment by cprice404** [comment]
@schwern have we tested the bottle from end to end?

**Comment by cprice404** [comment]
https://github.com/momentohq/homebrew-tap/actions/runs/3691064937/jobs/6248716598

**Comment by cprice404** [comment]
This branch has the rust builds working and the ability to test on PR:

https://github.com/momentohq/momento-cli/pull/214

It's failing when it tries to update the homebrew formula because it has a bad url, but that's probably a good thing.

As I look into this, I think we probably want to create a second homebrew formula for now with a temporary name so that we don't break the existing one while we work through it.  I think the end game from here is just to produce a formula that looks like this:

https://github.com/SpectralOps/homebrew-tap/blob/master/teller.rb#L22

it's not clear to me whether the plugin that we are trying to use in the current experimental workflow (`mislav/bump-homebrew-formula-action@v1`) actually has support for this.

I think for now I will just try to create a new formula by making a direct PR to our tap repo and prove that we can get it working like that.  If that works then we can fill in the blanks about how to generate/update the formula.
